api_auth:
    type:     rest
    resource: AuthBundle\Controller\AuthApiController
    prefix: /api
    defaults:
        _format: json

api_user:
    type:     rest
    resource: AuthBundle\Controller\UserController
    prefix: /api
    defaults:
        _format: json
