login:
    path:      /login
    defaults:  { _controller: AuthBundle:Security:login }

security_login_check:
    path:      /login_check

logout:
    path:      /logout

register:
    path:      /register
    defaults:  { _controller: AuthBundle:Registration:register }
