forgot_password:
    path:      /forgot/password
    defaults:  { _controller: AuthBundle:ForgotPassword:enterEmail }

send_password_email:
    path:     /forgot/password/check
    defaults:  { _controller: AuthBundle:ForgotPassword:sendPasswordResetEmail }

reset_password:
    path:     /reset/password/{token}
    defaults:  { _controller: AuthBundle:ForgotPassword:resetPassword }
