# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AuthBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_users:
            entity: { class: AuthBundle:User, property: email }
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /

    access_control:
          - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }

          # Secured part of the site
          # This config requires being logged for the whole site
          # and having the admin role for the admin part.
          # Change these rules to adapt them to your needs
          - { path: ^/admin/, role: ROLE_ADMIN }
          - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
