# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    app.form_login_authenticator:
        class: AuthBundle\Security\FormLoginAuthenticator
        arguments: ['@router', '@security.password_encoder']

    #base params : '@doctrine.orm.default_entity_manager', '@session', '@router', '@translator'

    app.service.user:
        class: AuthBundle\Services\UserService
        arguments: ['@doctrine.orm.default_entity_manager', '@session', '@router', '@translator', '@security.password_encoder', '@security.token_storage']

    auth.service.social.facebook:
        class: AuthBundle\Services\SocialServices\FacebookService
        arguments: ['@doctrine.orm.default_entity_manager', '@session', '@router', '@translator', '@app.service.user']

    msg.service.mailer:
        class: MessageBundle\Services\Mailers\MailerService
        arguments: ['@mailer', '%admin_address%']

    auth.service.confirmation:
        class: AuthBundle\Services\TokenServices\ConfirmationService
        arguments: ['@doctrine.orm.default_entity_manager', '@session', '@router', '@translator', '@app.service.user', '@msg.service.mailer', '%title%']

    auth.service.reset_password:
        class: AuthBundle\Services\TokenServices\ResetPasswordService
        arguments: ['@doctrine.orm.default_entity_manager', '@session', '@router', '@translator', '@app.service.user', '@msg.service.mailer', '%title%']

    page.service.category:
        class: PageBundle\Services\CategoryService
        arguments: ['@doctrine.orm.default_entity_manager', '@session', '@router', '@translator']

    page.service.article:
        class: PageBundle\Services\ArticleService
        arguments: ['@doctrine.orm.default_entity_manager', '@session', '@router', '@translator']

    jwt_token_authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        autowire: true
