mapping:
    class: PageBundle\Entity\Article
    aliased_properties: []
    hide_properties: []
    id_properties:
        - id
    urls:
        self: get_articles
    relationships:
        category:
          related: get_article_category #@Route name
