easy_admin:
    entities:
        User:
            class: AuthBundle\Entity\User
            controller: AuthBundle\Controller\UserAdminController
            edit:
                fields:
                    - email
                    - name
                    - roles
                    - activated
                    - facebookId
                    - googleId
                    - twitterId
            new:
                fields:
                    - email
                    - name
                    - roles
                    - password
                    - activated
                    - facebookId
                    - googleId
                    - twitterId
        Templates:
            class: MessageBundle\Entity\MessageTemplate
            controller: MessageBundle\Controller\MessageTemplateAdminController
            new:
                fields:
                    - subject
                    - { property: 'template', type: 'ckeditor' }
            edit:
                fields:
                    - subject
                    - { property: 'template', type: 'ckeditor' }

        Sending:
            class: MessageBundle\Entity\MessageUser
            controller: MessageBundle\Controller\MessageUserAdminController
            list:
                actions: ['-edit']
            new:
                fields:
                    - message
                    - property: 'users'
                      type: collection
                      type_options:
                          entry_type: 'AuthBundle\Form\UsersType'
                          allow_add: true
                          allow_delete: true
                          by_reference: false
