easy_admin:
    entities:
        User:
            class: AuthBundle\Entity\User
            controller: AuthBundle\Controller\UserAdminController
            edit:
                fields:
                    - email
                    - name
                    - roles
                    - activated
                    - facebookId
                    - googleId
                    - twitterId
            new:
                fields:
                    - email
                    - name
                    - password
                    - roles
                    - activated
                    - facebookId
                    - googleId
                    - twitterId
