easy_admin:
    entities:
        User:
            class: AuthBundle\Entity\User
            controller: AuthBundle\Controller\UserAdminController
            edit:
                fields:
                    - email
                    - name
                    - { property: 'role', label: 'Role', type: 'choice', type_options: { choices: { 'User': 'ROLE_USER', 'Admin': 'ROLE_ADMIN' } }}
                    - activated
                    - facebookId
                    - googleId
                    - twitterId
            new:
                fields:
                    - email
                    - name
                    - password
                    - { property: 'role', label: 'Role', type: 'choice', type_options: { choices: { 'User': 'ROLE_USER', 'Admin': 'ROLE_ADMIN' } }}
                    - activated
                    - facebookId
                    - googleId
                    - twitterId
        Templates:
            class: MessageBundle\Entity\MessageTemplate
            new:
                help: 'The list view overrides the global help message'
                fields:
                    - subject
                    - { property: 'template', type: 'ckeditor' }
            edit:
                help: 'The list view overrides the global help message'
                fields:
                    - subject
                    - { property: 'template', type: 'ckeditor' }

        Sending:
            class: MessageBundle\Entity\MessageUser
            controller: MessageBundle\Controller\MessageUserAdminController
            list:
                help: 'The list33333 view overrides the global help message'
                actions: ['new', 'delete', 'search']
            new:
                help: 'The list view overrides the global help message'
                fields:
                    - message
                    - property: 'users'
                      type: collection
                      type_options:
                          entry_type: 'AuthBundle\Form\UsersType'
                          allow_add: true
                          allow_delete: true
                          by_reference: false
