easy_admin:
    entities:
        User:
            class: AuthBundle\Entity\User
            controller: AuthBundle\Controller\UserAdminController
            edit:
                fields:
                    - email
                    - name
                    - roles
                    - activated
                    - facebookId
                    - googleId
                    - twitterId
            new:
                fields:
                    - email
                    - name
                    - password
                    - roles
                    - activated
                    - facebookId
                    - googleId
                    - twitterId
        Category:
            class: PageBundle\Entity\Category
            edit:
                fields:
                    - name
                    - description
                    - activated
            new:
                fields:
                    - name
                    - description
                    - activated
        Article:
            class: PageBundle\Entity\Article
            edit:
                fields:
                    - title
                    - category
                    - { property: 'content', type: 'ckeditor', required: true }
            new:
                fields:
                    - title
                    - category
                    - { property: 'content', type: 'ckeditor', required: true }
