api_category:
    type:     rest
    resource: PageBundle\Controller\CategoryController
    prefix: /api
    defaults:
        _format: json

api_article:
    type:     rest
    resource: PageBundle\Controller\ArticleController
    prefix: /api
    defaults:
        _format: json
