#mapping:
#    class: PageBundle\Entity\Category
#    alias: Category
#    aliased_properties:
#        name: name
#        description: description
#        activated: activated
#    hide_properties: []
#    id_properties:
#        - id
#    urls:
#        self: get_categories #@Route name
